# Análise das Intents

Este jupyter-notebook vai auxiliar na análise de detecção de intenções de seu chatbot.

### Configurando e Imports

In [1]:
import rasa
print("rasa: {}".format(rasa.__version__))

rasa: 1.2.0


### Treinando o modelo do Rasa NLU

* Para avaliar o bot o primeiro passo é treiner o seu chatbot. Mas não é necessário treinar a parte de conversão completa (rasa_core) apenas a parte de interpretação de mensagens (rasa_nlu).

* O comando `train-nlu` do Makefile executa o treinamento apenas do `rasa_nlu`

In [2]:
!make train-nlu -C $BOT_DIR_PATH

make: Entering directory '/work/bot'
rasa train nlu --fixed-model-name nlu
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tens

### Métodos de avaliação do chatbot

* O Rasa fornece vários métodos de avaliação e validação das `intents`, para verificar como utiliza-los, cada método fornece um log, imagem, gráfico ou arquivo com dados relevantes para interpretação do chatbot.

* O comando `rasa test` é a base para a avaliação do chatbot.

* Na célula abaixo a flag `-h` foi utilizada para mostrar as funções e a forma de uso de cada uma delas, mude seus valores e flags para ter as informações desejadas na sua análise.

* Atualmente o Rasa possui 2 modos, `evaluation` e `crossvalidation` que tem seções decicadas a eles neste jupyter notebook.

In [3]:
!rasa test nlu --help

usage: rasa test nlu [-h] [-v] [-vv] [--quiet] [-m MODEL] [-u NLU]
                     [--report [REPORT]] [--successes [SUCCESSES]]
                     [--errors ERRORS] [--histogram HISTOGRAM]
                     [--confmat CONFMAT] [-c CONFIG [CONFIG ...]]
                     [--cross-validation] [-f FOLDS] [-r RUNS]
                     [-p PERCENTAGES [PERCENTAGES ...]]

optional arguments:
  -h, --help            show this help message and exit
  -m MODEL, --model MODEL
                        Path to a trained Rasa model. If a directory is
                        specified, it will use the latest model in this
                        directory. (default: models)
  -u NLU, --nlu NLU     File or folder containing your NLU data. (default:
                        data)
  --report [REPORT]     Output path to save the intent/entity metrics report.
                        (default: None)
  --successes [SUCCESSES]
                        Output path to save successful predictions. (

### Evaluation

* O comando abaixo gera informações relevates para a validação das `intents` são elas:
    * Matriz de confuzão
    * Histograma
    * Erros de intents

In [4]:
!rasa test nlu -m $BOT_MODELS_PATH_NLU -u $BOT_INTENTS_PATH

/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

#### Matriz de Confuzão
* A matriz de confuzão mostra a correlação entre as intents.
* A diagonal principal tem forte correlação pois mostra a relação de uma intent **com ela mesma**
* O ideal é que não haja **nenhum valor** diferente de **0 fora da diagonal principal**.

In [5]:
from IPython.display import IFrame
IFrame(src='./confmat.png', width=900, height=700)

#### Erros

In [6]:
%cat errors.json

[
  {
    "text": "R$ 600000",
    "intent": "inform_preferences",
    "intent_prediction": {
      "name": "lead_data",
      "confidence": 0.8550623655319214
    }
  }
]

#### Histograma

* O histograma contém a distribuição da predições das `intents`

In [7]:
IFrame(src='./hist.png', width=900, height=700)

### Cross Validation

In [8]:
!rasa test nlu -u $BOT_INTENTS_PATH -c $BOT_CONFIG_PATH --cross-validation --folds 2 --report

/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

2019-08-13 19:04:45 INFO     rasa.nlu.test  - Accumulated test folds intent evaluation results:
2019-08-13 19:04:45 INFO     rasa.nlu.test  - Intent Evaluation: Only considering those 314 examples that have a defined intent out of 314 examples
2019-08-13 19:04:45 INFO     rasa.nlu.test  - Classification report saved to reports/intent_report.json.
2019-08-13 19:04:46 INFO     rasa.nlu.test  - Model prediction errors saved to errors.json.
2019-08-13 19:04:46 INFO     rasa.nlu.test  - Confusion matrix, without normalization: 
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 4 19  0  0  1  0  1  0  0  0  0  0  1  1  0  1]
 [ 3  0 16  0  0  0  0  0  4  0  0  0  0  0  0  0]
 [ 6  2  0  6  2  0  0  0  0  0  0  0  0  1  0  0]
 [ 3  0  0  0 18  0  2  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  1  1  0  0  0  0  0  0  0  0  1]
 [ 0  1  1  1  8  0 16  1  0  0  0  1  0  1  0  1]
 [ 5  0  1  0  1  0  0 10  1  1  0  0  1  1  0  0]
 [ 0  0  2  0  0  0  1  1  7  0  0  0  0  0  0  0]
 [ 0  1  0  

#### Histograma Cross Validation

In [10]:
IFrame(src='./hist.png', width=900, height=700)

## Referências:

O Rasa está em constante evolução, alguns links úteis para a construção deste jupyter-notebook e para a análise das `intents` são:

* [Evaluation](https://rasa.com/docs/nlu/evaluation/)